# Generated by Django 5.1.1 on 2024-10-05 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование линии бизнеса')),
            ],
            options={
                'verbose_name': 'Линия бизнеса',
                'verbose_name_plural': 'Линии бизнеса',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование риска')),
                ('value', models.IntegerField(verbose_name='Сумма страхования по данному риску')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Риски',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.lob', verbose_name='Линия бизнеса')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductMetaField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное/Не обязательно поле')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.lob', verbose_name='Линия бизнеса')),
            ],
            options={
                'verbose_name': 'Мета поле',
                'verbose_name_plural': 'Мета поля',
            },
        ),
        migrations.CreateModel(
            name='ProductRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_risks', to='products.product')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_products', to='products.risk')),
            ],
            options={
                'verbose_name': 'Продукт - Риск',
                'verbose_name_plural': 'Продукты - Риски',
            },
        ),
        migrations.AddField(
            model_name='lob',
            name='risks',
            field=models.ManyToManyField(related_name='lobs', to='products.risk', verbose_name='Риски метаполя'),
        ),
    ]
