# Generated by Django 5.1.1 on 2024-10-05 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Проект'), ('SIGNED', 'Подписан'), ('TERMINATED', 'Расторгнут')], default='DRAFT', max_length=255, verbose_name='Статус договора страхования')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания договора')),
                ('date_signet', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания договора')),
                ('date_begin', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала ответственности')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания ответственности')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая премия')),
                ('insurance_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая сумма')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая премия')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая премия')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Агент')),
                ('insured_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_person_contracts', to='agents.face', verbose_name='Код застрахованного лица')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_contracts', to='agents.face', verbose_name='Код собственника')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_holder_contracts', to='agents.face', verbose_name='Код страхователя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Страховой договор',
                'verbose_name_plural': 'Страховые договоры',
            },
        ),
        migrations.CreateModel(
            name='ContractRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая премия')),
                ('insurance_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договора страхования')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.risk', verbose_name='Страховые риски')),
            ],
            options={
                'verbose_name': 'Риск по договору',
                'verbose_name_plural': 'Рисков по договорам',
            },
        ),
    ]
