# Generated by Django 5.1.1 on 2024-10-05 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROJECT', 'Проект'), ('WORKS', 'Работает'), ('COMPLETED', 'Завершен'), ('TERMINATED', 'Расторгнут')], max_length=255, verbose_name='Статус агентского договора')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания договора')),
                ('date_begin', models.DateField(verbose_name='Дата начала действия')),
                ('date_end', models.DateField(verbose_name='Дата окончания действия')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименования подразделения')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counterparty_type', models.CharField(choices=[('NATURAL', 'Физическое лицо'), ('LEGAl', 'Юридическое лицо')], default='NATURAL', max_length=255, verbose_name='Тип контрагента')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('data_birth', models.DateField(verbose_name='Дата рождения')),
                ('name_legal_entity', models.CharField(max_length=255, verbose_name='Наименования юридического лица')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='AgentAgreements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.IntegerField(verbose_name='Ставка комиссии (проценты)')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Агент')),
                ('lob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.lob', verbose_name='Линия бизнеса')),
            ],
            options={
                'verbose_name': 'Условия агента',
                'verbose_name_plural': 'Условия агентов',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='agent',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.face', verbose_name='Контрагент'),
        ),
    ]
